### ISSUE TITLE
Google Image Charts API: Rotate x-axis labels

### ISSUE THREAD

**Issue by lopno** [lopno/invest-bot#29]
This repository has a function that generates graphs with [Google Image Charts](https://developers.google.com/chart/image/).
https://github.com/lopno/invest-bot/blob/master/lib/utils/graph.js#L20

Here is an example of a graph URL generated by the function: 
```
https://chart.googleapis.com/chart?chxt=x,y&chxr=0,0,7|1,90,120&chds=90,120&cht=lc&chd=t:92,110,100,109,100,102,118&chxl=0:|01-05-2017|02-05-2017|03-05-2017|04-05-2017|05-05-2017|06-05-2017|07-05-2017&chs=600x400&chco=FFFFFF&chls=3.5&chf=c,s,372987|bg,s,372987&chxs=0,N,FFFFFF,12,0,lt,FFFFFF,FFFFFF|1,N,FFFFFF,12,1,lt,FFFFFF,FFFFFF&chg=0,3.33,0
```

I would like to rotate the labels on the x-axis so they will be readable when they are very close together.
Update `getGraphLink()` in the file https://github.com/lopno/invest-bot/blob/master/lib/utils/graph.js

**Comment by benjaminrsherman** [comment]
Are you looking for a different URL which would provide this functionality?

**Comment by lopno** [comment]
@benjaminrsherman If you could provide a modified URL with the labels rotated, it would be easy to modify the function `getGraphLink()` that generates the URLs.
